
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Atul Adhikari  ## put your name
title: 'Data Science &amp; Product Enthusiast'  ## your title
location: Chicago , IL


## Professional Profiles
linkedin: https://www.linkedin.com/in/atul-adhikari-761a245b/  ## your linkedin account url
github: https://www.github.com/aca089/



# Update all the sections by editing the files inside _includes folder.
